### ISSUE TITLE
Unable to install pro tools

### ISSUE THREAD

**Issue by mbernemann** [RandomFractals/pro-data-tools#25]
Hi,

I became a sponsor but still was not able to install it.
There is a dead link on https://github.com/RandomFractals/pro-data-tools/blob/main/duckdb-tools.md#duckdb-pro-tools to https://github.com/RandomFractals/duckdb-pro-tools/releases. That is the only hint to how to install that I could find even after talking some time searching.

Regards

**Comment by RandomFractals** [comment]
Hi Martin,

I just got your sponsorship notification and sent you collaboration invites for all of the pro tools repositories.

You should be able to access them and download the corresponding pro versions of those VS Code extensions after you accept my repo invites from GitHub Notifications.

Thank you for sponsoring my work!

**Comment by mbernemann** [comment]
OK, thank you very much!
A hint in the installation instructions on waiting for an invite email can help people like me a lot.

**Comment by jboarman** [comment]
I agree with @mbernemann!  I spent more than 10 minutes trying sort out why I can't find where or how to download the pro tools.

@RandomFractals Please update the sponsorship page to help set expectations.  Thanks for sharing your work with the community!

**Comment by RandomFractals** [comment]
@jboarman will do in the next docs update. meanwhile, check your github notifications. I sent you collaborator invites for all the pro tools release and docs repositories. Thank you for sponsoring our data tools work!
